#!/bin/sh

root_dir=$(dirname $(readlink -f ${0}))
# zone="Europe/Zurich"
zone="Asia/Tokyo"

case "$1" in
  focus)
    xrandr --output eDP1 --off
    xrdb -merge $HOME/.Xresources
    sudo $root_dir/adjustwlan
    break
    ;;
  anywhere)
    xrandr --output eDP1
    xrdb -merge $HOME/.Xresources.eDP1
    xmodmap $HOME/.Xmodmap.surface
    sudo $root_dir/adjustwlan
    sudo $root_dir/adjustclock $zone
    break
    ;;
  *)
    echo "unknown argument given: $1"
esac
