#!/bin/sh

# curl --silent \
#   --header "Access-Token: ${PUSHBULLET_ACCESS_TOKEN}" \
#   https://api.pushbullet.com/v2/devices | \
#   jq .

# % pushb stockhorn "Hoi"
root_dir=$(dirname $(readlink -f ${0}))
source ${root_dir}/.env

case "${1}" in
  schafberg)
    iden="${PUSHBELLET_DEVICE_IDEN_SCHAFBERG}"
    ;;
  klewenalp)
    iden="${PUSHBELLET_DEVICE_IDEN_KLEWENALP}"
    ;;
  alphubel)
    iden="${PUSHBELLET_DEVICE_IDEN_ALPHUBEl}"
    ;;
  stockhorn)
    iden="${PUSHBELLET_DEVICE_IDEN_STOCKHORN}"
    ;;
  *)
    exit 1
    ;;
esac

body="${2}"
curl --silent \
  --header "Access-Token: ${PUSHBULLET_ACCESS_TOKEN}" \
  --header "Content-Type: application/json" \
  --request POST \
  --data-binary "{
    \"device_iden\": \"${iden}\",
    \"title\": \"Notice\",
    \"type\": \"note\",
    \"body\": \"${body}\"
  }" \
  https://api.pushbullet.com/v2/pushes | \
  jq .
