#!/bin/sh

set -eux

# rustup component add rust-src

# e.g. setup-rust-analyzer 2022-10-17
release="${1:-2022-10-17}"

toolchain="stable"
platform="x86_64-unknown-linux-gnu"

# repository
organization="rust-analyzer"
name="rust-analyzer"
repo_url="https://github.com/${organization}/${name}"
download_url="${repo_url}/releases/download/${release}/${name}-${platform}.gz"

location="$HOME/.atelier/bin"

curl -sL $download_url -o $location/$name.gz
gunzip $location/$name.gz

chmod +x $location/$name

set +x

output=$($location/$name --version)
if [ "${output:0:${#name}}" != "${name}" ]; then
  echo "---> Something wrong :'("
  exit 2
fi

echo "${output}"
