#!/bin/sh

zone="${1}"
script_dir="$(dirname $(readlink -f "${0}"))"

if [ "${zone}" != "Europe/Zurich" ] && [ "${zone}" != "Asia/Tokyo" ]; then
  echo "Unexpected zone name is given: ${zone} :'("
  exit 1
fi

sudo rm -fr /etc/timezone
sudo sh -c "echo \"${zone}\" > /etc/timezone"

sudo cp /usr/share/zoneinfo/$zone /etc/localtime

sudo rc-service ntp-client restart

$script_dir/adjustclock
