#!/bin/sh

set -e

# % timer <work> <rest>

w=${1:-25}
r=${2:-5}
t=3600 # milliseconds

if [ $# -eq 0 ]; then
  echo "Usage: timer <work> <rest>"
  exit 1
fi

dunstify -u normal "Start ${w} minutes" -t $t && \
  20min -w $w -r 0 && \
  dunstify -u normal "Stop" -t $t && \
  20min -w 0 -r $r && \
  dunstify -u normal "Finish" -t $t
